# Исключения

Ваш код на Dart может бросать и ловить исключения. Исключения - это ошибки, которые говорят, что что-то пошло не так. Если исключение не поймано, то область, которая вызвала исключение останавливается (также, как правило, останавливается и выполнение программы).

В отличие от Java, все исключения в Dart являются непроверенными. Методы не говорят о том, какие исключения они могут выбросить, и вы не обязаны ловить исключения.

Dart предоставляет типы [Exception](http://api.dartlang.org/dart_core/Exception.html) и [Error](http://api.dartlang.org/docs/continuous/dart_core/Error.html), и многие предопределенные подтипы. Конечно, вы также можете определить свое собственное исключение. 

Тем не менее, программа на Dart может бросить любой не **null** объект в качестве ошибки, а не только объекты класса **Exception** или  **Error**.

## throw

Пример выброса, распространения исключения:

```
[java]
throw new ExpectException('Значение должно быть больше нуля');
[/java]
```

Можно бросить любые объекты:

```
[java]
throw 'Лам больше нет!';
[/java]
```

Так как выброс исключения - это выражение, вы можете бросать исключения из оператора **=>**:

```
[java]
distanceTo(Point other) => throw new UnimplementedError();
[/java]
```

## catch

Отлов исключения прекращает его распространение. Отлов исключения дает возможность обработать его:

```
[java]
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  buyMoreLlamas();
}
[/java]
```

Прослушиваемый код может бросить различные исключения. Вы можете указать несколько операторов **catch**, каждый из которых будет отлавливать исключения определенного типа:

```
[java]
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  buyMoreLlamas();
} on Exception catch(e) {
  print('Неизвестное исключение: $e');
} catch(e) {
  print('Что-то непонятное: $e');
}
[/java]
```

Как видно выше, вы можете использовать **on** или **catch** или все вместе. Используйте **on** когда вым нужно указать тип исключения. Используйте **catch** когда нужно получить объект исключения.

## finally

Чтобы быть уверенным, что код выполнится несмотря на то, будет брошено исключение или нет, заключите его в блок **finally**. Если исключение не удалось отловить, то оно будет распространено после того, как выполнится блок **finally**:

```
[java]
try {
  breedMoreLlamas();
} finally {
  cleanLlamaStalls();  // Выполнится всегда.
}
[/java]
```

Блок **finally** выполняется после нужного **catch**:

```
[java]
try {
  breedMoreLlamas();
} catch(e) {
  print('Error: $e');  // Сначала обработаем ошибки
} finally {
  cleanLlamaStalls();  // После этого перейдем к finally.
}
[/java]
```